#!/usr/bin/env bun

import fs from "fs";
import path from "path";

const args = process.argv.slice(2);
const [command, rawName] = args;

if (!command || !rawName) {
  console.error("Usage: bun arona make:<type> <Name>");
  console.log("Types: command, config, middleware, helper, utils");
  process.exit(1);
}

const [_, type] = command.split(":");
const name = rawName.trim();
const fileName = name.toLowerCase() + ".ts";
const className = name;
const functionName = name.charAt((0)).toLowerCase() + name.slice(1);

const templates: Record<string, () => string> = {
  command: () =>
`import { type Command } from "../../types/Command";

export const ${functionName}: Command = {
  name: "${name.toLowerCase()}",
  description: "Deskripsi ${name}",
  usage: "",
  cmd: ["${name.toLowerCase()}"],
  category: "general",
  isMedia: false,
  isOnlyOwner: false,
  isOnlyGroup: false,
  isOnlyAdmin: false,
  isPremium: false,
  isAuth: false,
  async execute(sock, msg, args) {
    await sock.sendMessage(msg.key.remoteJid!, { text: "${name} works!" });
  },
};
`,
  config: () =>
`export const ${functionName} = {
  // Konfigurasi untuk ${name}
};
`,
  middleware: () =>
`import { type Middleware } from "../../types/Middleware";

export const ${functionName}: Middleware = {
  name: "${name.toLowerCase()}",
  async execute(sock, msg) {
    return true;
  },
  isAuth: false,
  isGroupOnly: false,
  isOnlyOwner: false,
  isOnlyAdmin: false,
};
`,
  helper: () =>
`export const ${functionName} = {
  
};
`,
  utils: () =>
`export const ${functionName} = () => {
  
};
`,
};

const targetDir: Record<string, string> = {
  command: "commands",
  config: "config",
  middleware: "middlewares",
  helper: "helpers",
  utils: "utils",
};

if (!type || !targetDir[type] || !(type in templates)) {
  console.error("Tipe yang didukung: " + Object.keys(templates).join(", "));
  process.exit(1);
}

const fullPath = path.join("./src", targetDir[type], fileName);

try {
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (fs.existsSync(fullPath)) {
    console.error("File sudah ada:", fullPath);
    process.exit(1);
  }
} catch (error) {
  console.error(error);
  process.exit(1);
}

fs.writeFileSync(fullPath, templates[type]());
console.log(`✅ Berhasil membuat ${type}: ${targetDir[type]}/${fileName}`);
process.exit(0);
